// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdvancedSearchController from "./advanced_search_controller"
application.register("advanced-search", AdvancedSearchController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import DocumentUploadController from "./document_upload_controller"
application.register("document-upload", DocumentUploadController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import PermissionsController from "./permissions_controller"
application.register("permissions", PermissionsController)

import SelectSearchController from "./select_search_controller"
application.register("select-search", SelectSearchController)

import MaskedInputController from "./masked_input_controller"
application.register("masked-input", MaskedInputController)
