// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ContractFieldsController from "./contract_fields_controller"
application.register("contract-fields", ContractFieldsController)

import DependentSpecializationsController from "./dependent_specializations_controller"
application.register("dependent-specializations", DependentSpecializationsController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
