name: Lint e Format Check

on:
  pull_request:
    branches: [master, main, develop]
  push:
    branches: [master, main]

jobs:
  lint-format:
    name: Verificar Qualidade de Código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Verificar formatação (Prettier)
        run: npm run format:check

      - name: Verificar qualidade (ESLint)
        run: npm run lint
        continue-on-error: true

      - name: Comentar no PR se houver erros
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Falha na verificação de código**\n\nEncontramos problemas de formatação ou lint.\n\n**Para corrigir:**\n```bash\nnpm run format  # Corrige formatação\nnpm run lint:fix  # Corrige problemas de lint\n```'
            })
